### ISSUE TITLE
Collaboration proposal

### ISSUE THREAD

**Issue by miguelperezcolom** [linkki-framework/linkki#2]
Hi,

first of all congratulations for your project. I think it is an excellent job.

I am currently finishing a first release of a model driven development framework which I think is highly related to your project.

The project is available at https://github.com/miguelperezcolom/mateu-mdd

Would you consider any kind of collaboration?

Thanks and best regards,

Miguel

**Comment by zrav** [comment]
Hello Miguel,

What kind of collaboration did you have in mind?
Our development of linkki is driven mainly by the requirements of our product and customer projects, but we would certainly review pull requests containing suitable additions and fixes to linkki. If you have other ideas, we'd be open for discussion.

Best regards and sorry for the delay,
Sebastian

**Comment by miguelperezcolom** [comment]
Hi Sebastian,

thanks for your email.

I think we face the same problems, as we are also using our framework for
our customer projects.

As far as I have seen of your project it seems that we are more or less
doing the same.

My idea was about joining efforts.

Perhaps we could agree some common requirements / specifications so we can
share components, or perhaps we could take advantage of the vaadin 10
migration (I think we both are working on v8) to create a new project with
the best of both frameworks and distribute the work between both sides.

I think it is a pity to do redundant job, so perhaps it would be better to
join forces and go farther together.

Best regards,

Miguel

**Comment by miguelperezcolom** [comment]
Hi Sebastian,

if you have some free time: https://youtu.be/VFMM283mD_Y

The vaadin's bakery app using mdd.


I thought perhaps this would be interesting for you.


Best regards,

Miguel

**Comment by cdir** [comment]
Hi Miguel,
I just watched your video and it realy helps to understand your framework. It realy looks like you have realy much impressive features and it looks very easy to implement an application.
However I think our goals are quite different:

As far I understood your framework is mainly used to get the UI for an Entiy model quite easy. That means that the model should be quite similar to the UI then you get a lot of standardized UI (that looks realy good!)

Our approach is an existing (and in most cases very complexive) domain model (normally we generate it using our other framework https://github.com/faktorips). But this domain model does not directly fit in any standard UI. For example one page shows data from different entities in different ways. That means we do not have any standard how an entity could be displayed. The configuration how to get a UI is much more fine graded.

In other words: we do not interpret the domain model. In linkki you seperate your app in sections. For every section you'll create one PMO (presentation model object). The PMO is just a POJO with a method for every field in this sections. These methods are annotated with the information which field should be rendered, on which position, the label of the field and so on.

Finally the power of linkki does not lie in creating UI. It is even possible to not use the annotations which declare the kind of field at all. The real power is the databinding (there the name comes from). The philosophy is that every piece of information that is configured at the field or transferred to the server is defined in the PMO, that means the PMO has all the state of the UI. That means we do not only bind the value. Everything is transferred by databinding: enabled, visible, availableValues, readOnly, style, icon, label etc. At the end you should never need to get the vaadin component to change anything, everything you might want to set at the vaadin component should be retrieved from a method in your PMO. That makes it realy easy to describe any UI with maximum flexibility. To get this flexibility it is very easy to describe your own field-annotation or aspect-annotation (an apsect is for enabled, visible etc. that means a binding for some property of the component we do not support in standard yet).

And because of everything is bound by the databinding there are some quite interesting additional abilities. For example if you need a kind of browse mode (the whole UI should be readonly maybe because of missing permissions) you simply extend the binding with a kind of interceptor that says everything is readonly and it do not have to ask the pmo.

So comming back to you :) Maybe you see that our goals are more in the details of very flexible and different UIs not in standardize the UI of a model. Of course that also means you need some more code to get the result :) I also considered that your framework may use linkki. But the only interesting part for you would be our binding mechanism and at the moment it is not very comfortable to create bindings without any annotation. That means that linkki is very flexible how the UI should looks like but it is not so flexible how it is described. And you will need a generic way to create the UI out of your entity model.

Concerning vaadin 8 and vaadin 10: we already have a branch with all the migration to vaadin 8. Unfortunately in our cusomers applications there are a lot of tables/grid. These grids are not that big but mostly consists of components and not only readonly text. And sometimes there are 3-5 grids on one page. Having that all we must admit that vaadin 8 with grid is far slower than vaadin 7 with tables. Finally the performance was that bad that we decided to not use vaadin 8 but look forward to vaadin 10. As far as there are some important features missing we still need to wait some time.

Kindly, Cornelius

**Comment by miguelperezcolom** [comment]
Hi Cornelius,

thank you very much for your email and for the explanation.

Thank you very much for watching the video, also. I hope it was not too
boring ;)


Regarding the PMOs, I think they are also implemented in Mateu MDD, though
I did not show them in the video as the video was just a kind of game, an
idea which came up after a vaadin training. It was like a challenge to see
how would it be to build the vaadin's bakery app with a MDD framework.


The truth is that I also worked on the same ideas that you expose though,
at the end, I finally took another way. I saw the concept a lot while
working with javafx, where a lot of aspect related characteristics are
exposed as properties, which can be bound and whatever.



Anyway, I am actually very much happy to realize that our projects are so
different. The more different they are, the more value we are giving to the
community.



Again thank you very much for your time, and I wish you the best of lucks
with your project.




Best regards,

Miguel
